[2024-04-22T18:13:43.094+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-04-22T18:13:43.102+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-04-22T18:13:43.103+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:13:43.118+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-01-01 00:00:00+00:00
[2024-04-22T18:13:43.122+0000] {standard_task_runner.py:60} INFO - Started process 231981 to run task
[2024-04-22T18:13:43.126+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmphj24hzrb']
[2024-04-22T18:13:43.127+0000] {standard_task_runner.py:88} INFO - Job 94: Subtask read_equipements
[2024-04-22T18:13:43.165+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-01-01T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:13:43.202+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:13:43.230+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-04-22T18:13:43.231+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:13:43.231+0000] {logging_mixin.py:188} INFO - intervals is ['None', '2024-01-01 00:00:00+00:00']
[2024-04-22T18:13:45.506+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 64, in read_equipements
    raise ValueError(f"No files found with good extensions {extensions}")
ValueError: No files found with good extensions ['.json']
[2024-04-22T18:13:45.509+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240101T000000, start_date=20240422T181343, end_date=20240422T181345
[2024-04-22T18:13:45.521+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 94 for task read_equipements (No files found with good extensions ['.json']; 231981)
[2024-04-22T18:13:45.544+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T18:13:45.561+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
