[2024-04-22T16:58:12.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-22T16:58:12.856+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-22T16:58:12.856+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:58:12.868+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-04-09 00:00:00+00:00
[2024-04-22T16:58:12.873+0000] {standard_task_runner.py:60} INFO - Started process 168249 to run task
[2024-04-22T16:58:12.875+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-04-09T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpnn9xe_q8']
[2024-04-22T16:58:12.876+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask read_equipements
[2024-04-22T16:58:12.909+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:58:12.964+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T00:00:00+00:00'
[2024-04-22T16:58:12.965+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:58:12.969+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:58:12.970+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:58:12.973+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240409T000000, start_date=20240422T165812, end_date=20240422T165812
[2024-04-22T16:58:12.982+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task read_equipements ('NoneType' object has no attribute 'date'; 168249)
[2024-04-22T16:58:13.008+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:58:13.023+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:20:02.315+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-22T18:20:02.323+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-22T18:20:02.324+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:20:02.337+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-04-09 00:00:00+00:00
[2024-04-22T18:20:02.340+0000] {standard_task_runner.py:60} INFO - Started process 239377 to run task
[2024-04-22T18:20:02.343+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-04-09T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmptkk02gq_']
[2024-04-22T18:20:02.343+0000] {standard_task_runner.py:88} INFO - Job 134: Subtask read_equipements
[2024-04-22T18:20:02.370+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-04-09T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:20:02.407+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:20:02.435+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T00:00:00+00:00'
[2024-04-22T18:20:02.437+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:20:02.437+0000] {logging_mixin.py:188} INFO - intervals is ['2024-04-09 00:00:00+00:00', '2024-04-09 00:00:00+00:00']
[2024-04-22T18:20:04.682+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:20:04.699+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240409T000000, start_date=20240422T182002, end_date=20240422T182004
[2024-04-22T18:20:04.721+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:20:04.746+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-04-09T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:20:04.753+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
