[2024-04-23T11:20:59.893+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-04-23T11:20:59.898+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-04-23T11:20:59.898+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:20:59.909+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-12 00:00:00+00:00
[2024-04-23T11:20:59.913+0000] {standard_task_runner.py:60} INFO - Started process 75845 to run task
[2024-04-23T11:20:59.915+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmplmqwph7m']
[2024-04-23T11:20:59.915+0000] {standard_task_runner.py:88} INFO - Job 249: Subtask gen_dates
[2024-04-23T11:20:59.943+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:20:59.970+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:21:00.089+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-04-23T11:21:00.089+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:21:04.100+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /intervalles?location=
[2024-04-23T11:21:05.736+0000] {python.py:202} INFO - Done. Returned value was: dates_20240312
[2024-04-23T11:21:05.752+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240312T000000, start_date=20240423T112059, end_date=20240423T112105
[2024-04-23T11:21:05.781+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:21:05.807+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T11:24:30.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-04-23T11:24:30.260+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-04-23T11:24:30.260+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:24:30.272+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-12 00:00:00+00:00
[2024-04-23T11:24:30.276+0000] {standard_task_runner.py:60} INFO - Started process 81055 to run task
[2024-04-23T11:24:30.278+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpchvzovcf']
[2024-04-23T11:24:30.278+0000] {standard_task_runner.py:88} INFO - Job 271: Subtask gen_dates
[2024-04-23T11:24:30.300+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-12T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:24:30.324+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:24:30.437+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-04-23T11:24:30.438+0000] {logging_mixin.py:188} INFO - {'start': '2024-03-12 00:00:00+00:00', 'end': '2024-04-23 11:24:30'}
[2024-04-23T11:24:30.438+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:24:32.489+0000] {python.py:202} INFO - Done. Returned value was: dates_20240312
[2024-04-23T11:24:32.507+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240312T000000, start_date=20240423T112430, end_date=20240423T112432
[2024-04-23T11:24:32.538+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:24:32.552+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
