[2024-04-22T16:57:10.971+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T16:57:10.977+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T16:57:10.977+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:57:10.989+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-20 00:00:00+00:00
[2024-04-22T16:57:10.992+0000] {standard_task_runner.py:60} INFO - Started process 166716 to run task
[2024-04-22T16:57:10.994+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp7220id64']
[2024-04-22T16:57:10.995+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask read_equipements
[2024-04-22T16:57:11.021+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:57:11.075+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-04-22T16:57:11.076+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:57:11.081+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:57:11.081+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:57:11.085+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240320T000000, start_date=20240422T165710, end_date=20240422T165711
[2024-04-22T16:57:11.095+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task read_equipements ('NoneType' object has no attribute 'date'; 166716)
[2024-04-22T16:57:11.126+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:57:11.142+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:39:33.640+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T17:39:33.647+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T17:39:33.647+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:39:33.663+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-20 00:00:00+00:00
[2024-04-22T17:39:33.669+0000] {standard_task_runner.py:60} INFO - Started process 203805 to run task
[2024-04-22T17:39:33.674+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpdv563lom']
[2024-04-22T17:39:33.675+0000] {standard_task_runner.py:88} INFO - Job 81: Subtask read_equipements
[2024-04-22T17:39:33.728+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:39:33.791+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-04-22T17:39:33.792+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:39:33.797+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:39:33.798+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 49, in read_equipements
    intervals =[context['prev_execution_date_success'], context['execution_date']] if context['prev_execution_date_success'] else [context['start_date'], context['execution_date']]
KeyError: 'start_date'
[2024-04-22T17:39:33.802+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240320T000000, start_date=20240422T173933, end_date=20240422T173933
[2024-04-22T17:39:33.813+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 81 for task read_equipements ('start_date'; 203805)
[2024-04-22T17:39:33.845+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:39:33.858+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:18:22.108+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T18:18:22.117+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-04-22T18:18:22.118+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:18:22.132+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-20 00:00:00+00:00
[2024-04-22T18:18:22.134+0000] {standard_task_runner.py:60} INFO - Started process 236930 to run task
[2024-04-22T18:18:22.137+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpdau26l05']
[2024-04-22T18:18:22.137+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask read_equipements
[2024-04-22T18:18:22.164+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-20T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:18:22.199+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:18:22.219+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-04-22T18:18:22.220+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:18:22.220+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-20 00:00:00+00:00', '2024-03-20 00:00:00+00:00']
[2024-04-22T18:18:24.314+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:18:24.331+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240320T000000, start_date=20240422T181822, end_date=20240422T181824
[2024-04-22T18:18:24.356+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:18:24.381+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-20T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:18:24.386+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
