[2024-04-23T12:58:11.815+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=103 [queued]>
[2024-04-23T12:58:11.826+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=103 [queued]>
[2024-04-23T12:58:11.826+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T12:58:11.839+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): push_in_redis> on 2024-04-23 11:54:48.966898+00:00
[2024-04-23T12:58:11.842+0000] {standard_task_runner.py:60} INFO - Started process 176571 to run task
[2024-04-23T12:58:11.844+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'push_in_redis', 'manual__2024-04-23T11:54:48.966898+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpgqrvwwzg', '--map-index', '103']
[2024-04-23T12:58:11.845+0000] {standard_task_runner.py:88} INFO - Job 475: Subtask push_in_redis
[2024-04-23T12:58:11.873+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=103 [running]> on host datalab-yasmine
[2024-04-23T12:58:12.025+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='push_in_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T11:54:48.966898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T11:54:48.966898+00:00'
[2024-04-23T12:58:12.025+0000] {pipeline_eq.py:90} INFO - start to push data in redis
[2024-04-23T12:58:13.689+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /extracted?location=
[2024-04-23T12:58:15.430+0000] {pipeline_eq.py:96} INFO - PIT411.json in redis
[2024-04-23T12:58:15.430+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-23T12:58:15.436+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=push_in_redis, map_index=103, execution_date=20240423T115448, start_date=20240423T125811, end_date=20240423T125815
[2024-04-23T12:58:15.479+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T12:58:15.494+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
