[2024-04-22T16:57:31.948+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T16:57:31.953+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T16:57:31.953+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:57:31.964+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-27 00:00:00+00:00
[2024-04-22T16:57:31.967+0000] {standard_task_runner.py:60} INFO - Started process 167213 to run task
[2024-04-22T16:57:31.969+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp1ckp1gq4']
[2024-04-22T16:57:31.969+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask read_equipements
[2024-04-22T16:57:31.996+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:57:32.051+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-22T16:57:32.052+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:57:32.057+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:57:32.058+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:57:32.061+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240327T000000, start_date=20240422T165731, end_date=20240422T165732
[2024-04-22T16:57:32.071+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task read_equipements ('NoneType' object has no attribute 'date'; 167213)
[2024-04-22T16:57:32.101+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:57:32.113+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:39:53.493+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T17:39:53.504+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T17:39:53.505+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:39:53.520+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-27 00:00:00+00:00
[2024-04-22T17:39:53.522+0000] {standard_task_runner.py:60} INFO - Started process 204307 to run task
[2024-04-22T17:39:53.525+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpdg083zva']
[2024-04-22T17:39:53.525+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask read_equipements
[2024-04-22T17:39:53.555+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:39:53.605+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-22T17:39:53.606+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:39:53.610+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:39:53.611+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 49, in read_equipements
    intervals =[context['prev_execution_date_success'], context['execution_date']] if context['prev_execution_date_success'] else [context['start_date'], context['execution_date']]
KeyError: 'start_date'
[2024-04-22T17:39:53.614+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240327T000000, start_date=20240422T173953, end_date=20240422T173953
[2024-04-22T17:39:53.624+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 88 for task read_equipements ('start_date'; 204307)
[2024-04-22T17:39:53.656+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:39:53.671+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:18:57.589+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T18:18:57.600+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-22T18:18:57.600+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:18:57.615+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-27 00:00:00+00:00
[2024-04-22T18:18:57.620+0000] {standard_task_runner.py:60} INFO - Started process 237779 to run task
[2024-04-22T18:18:57.623+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmppl9nlsiz']
[2024-04-22T18:18:57.624+0000] {standard_task_runner.py:88} INFO - Job 121: Subtask read_equipements
[2024-04-22T18:18:57.656+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-27T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:18:57.697+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:18:57.721+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-22T18:18:57.722+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:18:57.722+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-27 00:00:00+00:00', '2024-03-27 00:00:00+00:00']
[2024-04-22T18:18:59.877+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:18:59.894+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240327T000000, start_date=20240422T181857, end_date=20240422T181859
[2024-04-22T18:18:59.923+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:18:59.948+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-27T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:18:59.954+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
