[2024-04-22T16:56:54.151+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T16:56:54.157+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T16:56:54.158+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:56:54.169+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-15 00:00:00+00:00
[2024-04-22T16:56:54.172+0000] {standard_task_runner.py:60} INFO - Started process 166304 to run task
[2024-04-22T16:56:54.175+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpibv_6xy8']
[2024-04-22T16:56:54.175+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask read_equipements
[2024-04-22T16:56:54.216+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:56:54.266+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-22T16:56:54.267+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:56:54.272+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:56:54.272+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:56:54.276+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240315T000000, start_date=20240422T165654, end_date=20240422T165654
[2024-04-22T16:56:54.286+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task read_equipements ('NoneType' object has no attribute 'date'; 166304)
[2024-04-22T16:56:54.306+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:56:54.320+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:13:45.321+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T17:13:45.328+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T17:13:45.328+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:13:45.341+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-15 00:00:00+00:00
[2024-04-22T17:13:45.344+0000] {standard_task_runner.py:60} INFO - Started process 183661 to run task
[2024-04-22T17:13:45.347+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmph_n4uvrg']
[2024-04-22T17:13:45.348+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask read_equipements
[2024-04-22T17:13:45.385+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:13:45.471+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-22T17:13:45.472+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:13:45.473+0000] {logging_mixin.py:188} INFO - [<Proxy at 0x7fda4c8eb400 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fda4c91d5e0>, 'prev_execution_date_success', None)>, <Proxy at 0x7fda4cb9e380 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fda4c91d5e0>, 'execution_date', DateTime(2024, 3, 15, 0, 0, 0, tzinfo=Timezone('UTC')))>]
[2024-04-22T17:13:47.539+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:13:47.539+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:13:47.543+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240315T000000, start_date=20240422T171345, end_date=20240422T171347
[2024-04-22T17:13:47.554+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task read_equipements ('NoneType' object has no attribute 'date'; 183661)
[2024-04-22T17:13:47.564+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:13:47.580+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:17:58.622+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T18:17:58.630+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T18:17:58.630+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:17:58.643+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-15 00:00:00+00:00
[2024-04-22T18:17:58.646+0000] {standard_task_runner.py:60} INFO - Started process 236334 to run task
[2024-04-22T18:17:58.648+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpudh_au5s']
[2024-04-22T18:17:58.649+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask read_equipements
[2024-04-22T18:17:58.688+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:17:58.729+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:17:58.752+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-22T18:17:58.753+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:17:58.753+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-15 00:00:00+00:00', '2024-03-15 00:00:00+00:00']
[2024-04-22T18:18:00.765+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:18:00.781+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240315T000000, start_date=20240422T181758, end_date=20240422T181800
[2024-04-22T18:18:00.826+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:18:00.849+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-15T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:18:00.854+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:28:57.721+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T18:28:57.730+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-04-22T18:28:57.730+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:28:57.744+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-15 00:00:00+00:00
[2024-04-22T18:28:57.747+0000] {standard_task_runner.py:60} INFO - Started process 250030 to run task
[2024-04-22T18:28:57.749+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpdhwgycme']
[2024-04-22T18:28:57.750+0000] {standard_task_runner.py:88} INFO - Job 173: Subtask read_equipements
[2024-04-22T18:28:57.777+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-15T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:28:57.816+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:28:57.838+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-04-22T18:28:57.839+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:28:57.839+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-15 00:00:00+00:00', '2024-03-15 00:00:00+00:00']
[2024-04-22T18:28:59.793+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:28:59.811+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240315T000000, start_date=20240422T182857, end_date=20240422T182859
[2024-04-22T18:28:59.846+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:28:59.874+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-15T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:28:59.880+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
