[2024-04-23T11:59:40.641+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements manual__2024-04-23T11:54:48.966898+00:00 [queued]>
[2024-04-23T11:59:40.646+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements manual__2024-04-23T11:54:48.966898+00:00 [queued]>
[2024-04-23T11:59:40.647+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-23T11:59:40.656+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-04-23 11:54:48.966898+00:00
[2024-04-23T11:59:40.660+0000] {standard_task_runner.py:60} INFO - Started process 114654 to run task
[2024-04-23T11:59:40.663+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'manual__2024-04-23T11:54:48.966898+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpv412kjel']
[2024-04-23T11:59:40.664+0000] {standard_task_runner.py:88} INFO - Job 284: Subtask read_equipements
[2024-04-23T11:59:40.689+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements manual__2024-04-23T11:54:48.966898+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:59:40.847+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T11:54:48.966898+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T11:54:48.966898+00:00'
[2024-04-23T11:59:40.848+0000] {pipeline_eq.py:65} INFO - get date
[2024-04-23T11:59:40.848+0000] {rw.py:43} INFO - start to get objects in minio
[2024-04-23T11:59:40.848+0000] {rw.py:45} INFO - get objects
[2024-04-23T11:59:40.848+0000] {rw.py:48} INFO - get good objects
[2024-04-23T11:59:43.048+0000] {logging_mixin.py:188} INFO - {'start': '2024-04-23 11:54:48.966898+00:00', 'end': '2024-04-23 11:54:51'}
[2024-04-23T11:59:43.048+0000] {pipeline_eq.py:73} INFO - start to get objects in minio
[2024-04-23T11:59:43.048+0000] {logging_mixin.py:188} INFO - intervals is {'start': '2024-04-23 11:54:48.966898+00:00', 'end': '2024-04-23 11:54:51'}
[2024-04-23T12:00:09.926+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 80, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and datetime.strptime(intervals["start"], "%Y-%m-%d %H:%M:%S")<obj.last_modified <=  datetime.strptime(intervals["end"], "%Y-%m-%d %H:%M:%S") ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 80, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and datetime.strptime(intervals["start"], "%Y-%m-%d %H:%M:%S")<obj.last_modified <=  datetime.strptime(intervals["end"], "%Y-%m-%d %H:%M:%S") ]
  File "/home/yasmine/.pyenv/versions/3.8.16/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/yasmine/.pyenv/versions/3.8.16/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .966898+00:00
[2024-04-23T12:00:09.929+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240423T115448, start_date=20240423T115940, end_date=20240423T120009
[2024-04-23T12:00:09.942+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 284 for task read_equipements (unconverted data remains: .966898+00:00; 114654)
[2024-04-23T12:00:09.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T12:00:09.999+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
