[2024-04-23T13:21:01.560+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=385 [queued]>
[2024-04-23T13:21:01.585+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=385 [queued]>
[2024-04-23T13:21:01.585+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T13:21:01.679+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): push_in_redis> on 2024-04-23 11:54:48.966898+00:00
[2024-04-23T13:21:01.683+0000] {standard_task_runner.py:60} INFO - Started process 213897 to run task
[2024-04-23T13:21:01.685+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'push_in_redis', 'manual__2024-04-23T11:54:48.966898+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp9vk885i_', '--map-index', '385']
[2024-04-23T13:21:01.686+0000] {standard_task_runner.py:88} INFO - Job 757: Subtask push_in_redis
[2024-04-23T13:21:01.709+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.push_in_redis manual__2024-04-23T11:54:48.966898+00:00 map_index=385 [running]> on host datalab-yasmine
[2024-04-23T13:21:01.754+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='push_in_redis' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T11:54:48.966898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T11:54:48.966898+00:00'
[2024-04-23T13:21:01.755+0000] {pipeline_eq.py:90} INFO - start to push data in redis
[2024-04-23T13:21:03.558+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /extracted?location=
[2024-04-23T13:21:05.324+0000] {pipeline_eq.py:96} INFO - FSL031.json in redis
[2024-04-23T13:21:05.324+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-23T13:21:05.334+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=push_in_redis, map_index=385, execution_date=20240423T115448, start_date=20240423T132101, end_date=20240423T132105
[2024-04-23T13:21:05.362+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T13:21:05.373+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
