[2024-04-22T16:56:51.463+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T16:56:51.475+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T16:56:51.476+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T16:56:51.501+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-14 00:00:00+00:00
[2024-04-22T16:56:51.510+0000] {standard_task_runner.py:60} INFO - Started process 166218 to run task
[2024-04-22T16:56:51.513+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpexz8_w10']
[2024-04-22T16:56:51.514+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask read_equipements
[2024-04-22T16:56:51.554+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T16:56:51.610+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-04-22T16:56:51.611+0000] {pipeline_eq.py:47} INFO - start to get objects in minio
[2024-04-22T16:56:51.616+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T16:56:51.616+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 48, in read_equipements
    intervals =[context['prev_execution_date_success'].date, context['execution_date'].date]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T16:56:51.620+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240314T000000, start_date=20240422T165651, end_date=20240422T165651
[2024-04-22T16:56:51.629+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 20 for task read_equipements ('NoneType' object has no attribute 'date'; 166218)
[2024-04-22T16:56:51.646+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T16:56:51.660+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T17:13:39.309+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T17:13:39.314+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T17:13:39.315+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T17:13:39.326+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-14 00:00:00+00:00
[2024-04-22T17:13:39.329+0000] {standard_task_runner.py:60} INFO - Started process 183530 to run task
[2024-04-22T17:13:39.332+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmp_01svn9h']
[2024-04-22T17:13:39.333+0000] {standard_task_runner.py:88} INFO - Job 75: Subtask read_equipements
[2024-04-22T17:13:39.361+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T17:13:39.411+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-04-22T17:13:39.412+0000] {pipeline_eq.py:48} INFO - start to get objects in minio
[2024-04-22T17:13:39.412+0000] {logging_mixin.py:188} INFO - [<Proxy at 0x7fd8e69fb380 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fd8e6a375e0>, 'prev_execution_date_success', None)>, <Proxy at 0x7fd8e6a699c0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fd8e6a375e0>, 'execution_date', DateTime(2024, 3, 14, 0, 0, 0, tzinfo=Timezone('UTC')))>]
[2024-04-22T17:13:41.808+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2024-04-22T17:13:41.808+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in read_equipements
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
  File "/home/yasmine/Documents/FREELANCE/knowledge-base-siaap/dags/kbs/custom_dags/pipeline_eq.py", line 60, in <listcomp>
    good_objects = [obj.object_name for obj in objects if obj.object_name.lower().endswith(tuple(extensions)) and obj.last_modified.date in [intervals[0].date, intervals[1].date] ]
AttributeError: 'NoneType' object has no attribute 'date'
[2024-04-22T17:13:41.812+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240314T000000, start_date=20240422T171339, end_date=20240422T171341
[2024-04-22T17:13:41.823+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 75 for task read_equipements ('NoneType' object has no attribute 'date'; 183530)
[2024-04-22T17:13:41.830+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T17:13:41.848+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:17:53.945+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T18:17:53.956+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T18:17:53.956+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:17:53.976+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-14 00:00:00+00:00
[2024-04-22T18:17:53.979+0000] {standard_task_runner.py:60} INFO - Started process 236206 to run task
[2024-04-22T18:17:53.982+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpm5e7ehd_']
[2024-04-22T18:17:53.982+0000] {standard_task_runner.py:88} INFO - Job 108: Subtask read_equipements
[2024-04-22T18:17:54.013+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:17:54.051+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:17:54.071+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-04-22T18:17:54.071+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:17:54.072+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-14 00:00:00+00:00', '2024-03-14 00:00:00+00:00']
[2024-04-22T18:17:56.470+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:17:56.486+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240314T000000, start_date=20240422T181753, end_date=20240422T181756
[2024-04-22T18:17:56.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:17:56.546+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-14T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:17:56.551+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T18:28:51.646+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T18:28:51.654+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-22T18:28:51.654+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-22T18:28:51.668+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): read_equipements> on 2024-03-14 00:00:00+00:00
[2024-04-22T18:28:51.671+0000] {standard_task_runner.py:60} INFO - Started process 249897 to run task
[2024-04-22T18:28:51.673+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'read_equipements', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpmd__dar6']
[2024-04-22T18:28:51.674+0000] {standard_task_runner.py:88} INFO - Job 172: Subtask read_equipements
[2024-04-22T18:28:51.703+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.read_equipements scheduled__2024-03-14T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-22T18:28:51.742+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-22T18:28:51.764+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='read_equipements' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-04-22T18:28:51.765+0000] {pipeline_eq.py:53} INFO - start to get objects in minio
[2024-04-22T18:28:51.765+0000] {logging_mixin.py:188} INFO - intervals is ['2024-03-14 00:00:00+00:00', '2024-03-14 00:00:00+00:00']
[2024-04-22T18:28:54.296+0000] {python.py:202} INFO - Done. Returned value was: []
[2024-04-22T18:28:54.314+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=read_equipements, execution_date=20240314T000000, start_date=20240422T182851, end_date=20240422T182854
[2024-04-22T18:28:54.334+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T18:28:54.363+0000] {abstractoperator.py:567} INFO - Marking <TaskInstance: pipeline_eq.push_in_redis scheduled__2024-03-14T00:00:00+00:00 [None]> as SKIPPED since the map has 0 values to expand
[2024-04-22T18:28:54.368+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
