[2024-04-23T11:20:44.795+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-04-23T11:20:44.803+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-04-23T11:20:44.803+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:20:44.817+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-09 00:00:00+00:00
[2024-04-23T11:20:44.821+0000] {standard_task_runner.py:60} INFO - Started process 75448 to run task
[2024-04-23T11:20:44.823+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmprmss5n3h']
[2024-04-23T11:20:44.824+0000] {standard_task_runner.py:88} INFO - Job 246: Subtask gen_dates
[2024-04-23T11:20:44.844+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:20:44.871+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:20:44.984+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2024-04-23T11:20:44.984+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:20:46.485+0000] {connectionpool.py:874} WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /intervalles?location=
[2024-04-23T11:20:48.122+0000] {python.py:202} INFO - Done. Returned value was: dates_20240309
[2024-04-23T11:20:48.141+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240309T000000, start_date=20240423T112044, end_date=20240423T112048
[2024-04-23T11:20:48.167+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:20:48.181+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-23T11:24:16.155+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-04-23T11:24:16.161+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2024-04-23T11:24:16.161+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-23T11:24:16.172+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): gen_dates> on 2024-03-09 00:00:00+00:00
[2024-04-23T11:24:16.176+0000] {standard_task_runner.py:60} INFO - Started process 80685 to run task
[2024-04-23T11:24:16.179+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline_eq', 'gen_dates', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/kbs/custom_dags/pipeline_eq.py', '--cfg-path', '/tmp/tmpw1prvr_q']
[2024-04-23T11:24:16.179+0000] {standard_task_runner.py:88} INFO - Job 268: Subtask gen_dates
[2024-04-23T11:24:16.215+0000] {task_command.py:423} INFO - Running <TaskInstance: pipeline_eq.gen_dates scheduled__2024-03-09T00:00:00+00:00 [running]> on host datalab-yasmine
[2024-04-23T11:24:16.249+0000] {logging_mixin.py:188} WARNING - /home/yasmine/.local/share/virtualenvs/knowledge-base-siaap-WvBZnYs-/lib/python3.8/site-packages/airflow/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-04-23T11:24:16.373+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pipeline_eq' AIRFLOW_CTX_TASK_ID='gen_dates' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2024-04-23T11:24:16.374+0000] {logging_mixin.py:188} INFO - {'start': '2024-03-09 00:00:00+00:00', 'end': '2024-04-23 11:24:16'}
[2024-04-23T11:24:16.374+0000] {rw.py:84} INFO - Starting to save files into Minio
[2024-04-23T11:24:18.474+0000] {python.py:202} INFO - Done. Returned value was: dates_20240309
[2024-04-23T11:24:18.492+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=pipeline_eq, task_id=gen_dates, execution_date=20240309T000000, start_date=20240423T112416, end_date=20240423T112418
[2024-04-23T11:24:18.520+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-23T11:24:18.534+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
